/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package persistencia_semdao;

import java.awt.event.ActionEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author vitor
 */
public class TelaProjeto extends javax.swing.JFrame {

    /**
     * Creates new form Persistencia_SemDAO1
     */
    public TelaProjeto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotNext = new javax.swing.JButton();
        BoxOption = new javax.swing.JComboBox<>();
        NameProject = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        CampEscolha = new javax.swing.JLabel();
        txtDesc = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        boxId = new javax.swing.JTextField();
        BoxDesc = new javax.swing.JTextField();
        BoxPreco = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotNext.setText("Avançar");
        BotNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotNextActionPerformed(evt);
            }
        });

        BoxOption.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        BoxOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Ação..", "1 - Cadastrar ", "2 - Atualizar ", "3 - Deletar ", "4 - Consultar 1 Produto", "5 - Consultar produtos cadastrados" }));
        BoxOption.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                BoxOptionItemStateChanged(evt);
            }
        });
        BoxOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxOptionActionPerformed(evt);
            }
        });

        NameProject.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        NameProject.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameProject.setText("Projeto 2.3");

        txtId.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        txtId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtId.setText("ID");

        CampEscolha.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        CampEscolha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CampEscolha.setText("Escolha a ação desejada");

        txtDesc.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        txtDesc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDesc.setText("DESCRIÇÃO");

        txtPreco.setFont(new java.awt.Font("NSimSun", 0, 18)); // NOI18N
        txtPreco.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtPreco.setText("VALOR");
        txtPreco.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtPrecoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        boxId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxIdActionPerformed(evt);
            }
        });

        BoxDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxDescActionPerformed(evt);
            }
        });

        BoxPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxPrecoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotNext))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CampEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BoxOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BoxDesc))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BoxPreco))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(boxId))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(NameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(NameProject, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BoxOption, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(CampEscolha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId)
                    .addComponent(boxId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDesc)
                    .addComponent(BoxDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPreco)
                    .addComponent(BoxPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(BotNext)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotNextActionPerformed(ActionEvent evt) {//GEN-FIRST:event_BotNextActionPerformed
        ProdutoDao pdao = new ProdutoDao();
        Produto p = new Produto();

        switch (BoxOption.getSelectedIndex()) {
            case 0:
                JOptionPane.showMessageDialog(null, "Selecione uma opção acima");
                break;
            case 1:

                p.setDescricao(BoxDesc.getText());
                p.setPreco(Double.parseDouble(BoxPreco.getText()));
                try {
                    pdao.cadastrar(p);
                    JOptionPane.showMessageDialog(null,"Produto Cadastrado com sucesso !");

                } catch (ClassNotFoundException | SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Deu errado irmao.. "  + ex.getMessage());
                    System.out.println("Chegou aqui.");
                }
                break;
            case 2:
                p.setDescricao(BoxDesc.getText());
                p.setPreco(Double.parseDouble(BoxPreco.getText()));
                p.setId((int) Double.parseDouble(boxId.getText()));
                try {
                    pdao.atualizar(p);
                    JOptionPane.showMessageDialog(null,"Produto Atualizado com sucesso !");
                } catch(ClassNotFoundException | SQLException ex){
                    JOptionPane.showMessageDialog(null,"Erro Irmao.. " + ex.getMessage());
                }
                break;
            case 3:
                p.setId((int) Double.parseDouble(boxId.getText()));
                try {
                    pdao.delete(p);
                    JOptionPane.showMessageDialog(null,"Produto Deletado !");
                } catch (ClassNotFoundException | SQLException ex){
                    JOptionPane.showMessageDialog(null,"Erro Irmao... "  + ex.getMessage());
                }
                break;
            case 4:
                // Define o ID do Objeto produto (Poderia ser um STRING que seria mt superior
                p.setId((int) Double.parseDouble(boxId.getText()));
                
                try {
                    // Cria um objeto produto e salva os dados retornados do método pdao.consultarById()
                    Produto result = pdao.consultarById(p);
                    JOptionPane.showMessageDialog(null, "Descricao: " + result.getDescricao());
                } catch (ClassNotFoundException | SQLException ex){
                    JOptionPane.showMessageDialog(null,"Erro Irmao... "  + ex.getMessage());
                }
                break;
            default:
                try {
                    List<Produto> listaproduto = pdao.consultarTodos();
                    for (Produto p1 : listaproduto) {
                        JOptionPane.showMessageDialog(null, "Descricao: " + p1.getDescricao() + "\nPreço: " + p1.getPreco() + "\nId: " + p1.getId());
                    }
                } catch (ClassCastException | SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Erro Irmao... "  + ex.getMessage());

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(TelaProjeto.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;
        }
        
        
    }//GEN-LAST:event_BotNextActionPerformed

    private void BoxDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxDescActionPerformed

    private void boxIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxIdActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_boxIdActionPerformed

    private void BoxOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxOptionActionPerformed

    }//GEN-LAST:event_BoxOptionActionPerformed

    private void BoxOptionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_BoxOptionItemStateChanged
        switch (BoxOption.getSelectedIndex()) {
            case 0: {
                boxId.setVisible(false);
                BoxDesc.setVisible(false);
                BoxPreco.setVisible(false);

                txtId.setVisible(false);
                txtDesc.setVisible(false);
                txtPreco.setVisible(false);
            }
            case 1: {
                txtId.setVisible(false);
                txtDesc.setVisible(true);
                txtPreco.setVisible(true);

                boxId.setVisible(false);
                BoxDesc.setVisible(true);
                BoxPreco.setVisible(true);
            }
            case 2: {
                txtId.setVisible(true);
                txtDesc.setVisible(true);
                txtPreco.setVisible(true);

                boxId.setVisible(true);
                BoxDesc.setVisible(true);
                BoxPreco.setVisible(true);
            }
            case 3: {
                txtDesc.setVisible(false);
                txtPreco.setVisible(false);
                txtId.setVisible(true);

                boxId.setVisible(true);
                BoxDesc.setVisible(false);
                BoxPreco.setVisible(false);

            }
            case 4: {
                boxId.setVisible(true);
                BoxDesc.setVisible(false);
                BoxPreco.setVisible(false);

                txtId.setVisible(true);
                txtDesc.setVisible(false);
                txtPreco.setVisible(false);
            }
            default: {
                boxId.setVisible(false);
                BoxDesc.setVisible(false);
                BoxPreco.setVisible(false);
                txtId.setVisible(false);
                txtDesc.setVisible(false);
                txtPreco.setVisible(false);
            }
        }
    }//GEN-LAST:event_BoxOptionItemStateChanged

    private void BoxPrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxPrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxPrecoActionPerformed

    private void txtPrecoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtPrecoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaProjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotNext;
    private javax.swing.JTextField BoxDesc;
    private javax.swing.JComboBox<String> BoxOption;
    private javax.swing.JTextField BoxPreco;
    private javax.swing.JLabel CampEscolha;
    private javax.swing.JLabel NameProject;
    private javax.swing.JTextField boxId;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtPreco;
    // End of variables declaration//GEN-END:variables
}
